# yaml-language-server: $schema=https://taskfile.dev/schema.json
# https://taskfile.dev

version: "3"

vars:
  CURRENT_DATE:
    sh: date +"%Y-%m-%dT%H-%M-%S%Z"
  CAL_VER_DATE:
    sh: date -u +"%Y.%m%d.%H%M"

tasks:
  default:
    desc: Show available tasks
    cmds:
      - task --list-all

  help:
    desc: Show this help message
    cmds:
      - task --list-all

  hog:
    cmds:
      - |
        trufflehog git file://. \
          --since-commit HEAD \
          --only-verified \
          --fail \
          --no-update

  mr:
    desc: "Create Merge Request and Merge"
    cmds:
      - glab mr create --fill --fill-commit-body --yes
      - sleep 2
      - glab mr merge -d

  pre:
    cmds:
      - pre-commit autoupdate
      - pre-commit gc
      - pre-commit run -a

  push:
    cmds:
      - |
        if [[ $(git rev-parse --abbrev-ref HEAD) == "main" ]]; then
          git switch --create {{.CURRENT_DATE}}
        fi
      - git add .
      - git commit -m "{{.CURRENT_DATE}}"
      - git push

  pr:
    cmds:
      - gh pr create --fill-verbose
      - sleep 2
      - gh pr merge --delete-branch --merge

  radar:
    cmds:
      - vault-radar scan git pre-commit

  tag:*:*:
    desc: "Create a signed tag with a message"
    vars:
      TAG_NAME: "{{index .MATCH 0}}"
      TAG_MESSAGE: "{{index .MATCH 1}}"
    cmds:
      - git push
      - git tag -s {{.TAG_NAME}} -m "{{.TAG_MESSAGE}}"
      - git push --tags

  tag:*:
    desc: "Create a signed tag with tag as message"
    vars:
      TAG_NAME: "{{index .MATCH 0}}"
    cmds:
      - git push
      - git tag -s {{.TAG_NAME}} -m "{{.TAG_NAME}}"
      - git push --tags

  tag0:
    desc: "Create first tag on repo"
    cmds:
      - git push
      - git tag -s v0.0.0 -m "v0.0.0 - First Tag 🤠"
      - git push --tags

  tagauto:
    desc: "Create a signed tag with auto semantic versioning"
    cmds:
      - git push
      - |
        LAST_TAG=$(git describe --tags $(git rev-list --tags --max-count=1))
        if [[ -z "$LAST_TAG" ]]; then
          git tag -s v0.0.0 -m "v0.0.0 - First Tag 🤠"
        else
          NEW_TAG="v$(autotag -vn --scheme=conventional)"
          git tag -s "$NEW_TAG" -m "$NEW_TAG"
        fi
      - git push --tags

  tagcal:
    desc: "Create a signed tag with calendar versioning"
    cmds:
      - git push
      - git tag -s v{{.CAL_VER_DATE}} -m "v{{.CAL_VER_DATE}}"
      - git push --tags
