# yaml-language-server: $schema=https://taskfile.dev/schema.json
# https://taskfile.dev

version: "3"

dotenv: [".envrc"]

vars:
  CURRENT_DATE:
    sh: date +"%Y-%m-%dT%H:%M:%S%Z"

tasks:
  default:
    cmds:
      - task: pre

  hog:
    cmds:
      - trufflehog git file://. --since-commit HEAD --only-verified --fail

  log:
    cmds:
      - |
        git-chglog --next-tag v$(autotag -vn --scheme=conventional) -o CHANGELOG.md
        git add CHANGELOG.md
        pre-commit run end-of-file-fixer || true
        git commit -m 'chore: update CHANGELOG.md'

  pre:
    cmds:
      - pre-commit autoupdate
      - pre-commit run -a

  push:
    cmds:
      - git add .
      - git commit -m "{{.CURRENT_DATE}}"
      - git push
    silent: true

  tag:
    cmds:
      - git push
      - git tag -s {{.CLI_ARGS}} -m "{{.CLI_ARGS}}"
      - git push --tags
