name: Tag and Release
on:
  push:
    branches:
      - main

permissions:
  issues: write
  contents: write
  pull-requests: write

jobs:
  tag-release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: fetch tags
        run: git fetch --force --tags

      - name: install autotag binary
        run: |
          curl -sL https://git.io/autotag-install | sudo sh -s -- -b /usr/local/bin

      - name: increment tag and create release
        run: |
          set -eou pipefail

          new_version=$(autotag -vn --scheme=conventional)
          gh release create v"${new_version}" --target main --title "v${new_version}" --generate-notes
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
